# Generated by Django 5.0.3 on 2024-05-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0036_userprofile_auto_tagging_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
    ]
