# Generated by Django 5.1.5 on 2025-02-09 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0037_bookmark_pinned"),
        ("bookmarks", "0043_userprofile_collapse_side_panel"),
    ]

    operations = []
